name: VPS Pentest Environment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # كل 6 ساعات

jobs:
  setup-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Go, Python, and Pentest Tools
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip python3-venv git curl wget unzip build-essential

          # Install Go
          LATEST_GO=$(curl -s https://go.dev/VERSION?m=text | head -n 1)
          wget "https://go.dev/dl/${LATEST_GO}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf "${LATEST_GO}.linux-amd64.tar.gz"
          export PATH=$PATH:/usr/local/go/bin:~/go/bin
          echo 'export PATH=$PATH:/usr/local/go/bin:~/go/bin' >> ~/.bashrc
          go version

          # Install ffuf
          /usr/local/go/bin/go install github.com/ffuf/ffuf/v2@latest
          sudo ln -sf ~/go/bin/ffuf /usr/local/bin/ffuf

          # Install httpx (ProjectDiscovery)
          /usr/local/go/bin/go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          sudo ln -sf ~/go/bin/httpx /usr/local/bin/httpx

          # Install dirsearch
          mkdir -p ~/tools
          git clone https://github.com/maurosoria/dirsearch.git ~/tools/dirsearch
          pip3 install -r ~/tools/dirsearch/requirements.txt
          sudo ln -sf ~/tools/dirsearch/dirsearch.py /usr/local/bin/dirsearch
          sudo chmod +x /usr/local/bin/dirsearch

          # Install SecLists
          mkdir -p ~/wordlists
          git clone https://github.com/danielmiessler/SecLists.git ~/wordlists/SecLists

          echo "✅ All tools installed successfully!"
          echo "-------------------------"
          ffuf -version
          httpx -version
          python3 /usr/local/bin/dirsearch -h | head -n 5


      - name: Verify SSH Access
        run: |
          echo "✅ VPS ready with pentest tools!"
          echo "IP: $TAILSCALE_IP"
          echo "User: root"
          echo "Pass: admin@123"

      - name: Keep VPS Alive
        run: |
          while true; do
            echo "[$(date)] VPS running with pentest tools..."
            sleep 300
          done
