name: VPS Pentest Environment2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # كل 6 ساعات

jobs:
  setup-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install & Configure SSH
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:admin@123" | sudo chpasswd
          sudo sed -i '/^PermitRootLogin/d' /etc/ssh/sshd_config || true
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config > /dev/null
          sudo systemctl restart ssh
          echo "✅ SSH user: root | pass: admin@123"

      - name: Install Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey="${TAILSCALE_AUTH_KEY}" --hostname=vps-${{ github.run_id }} || true
          tsIP=$(tailscale ip -4 | head -n 1 || true)
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV
          echo "✅ Tailscale IP: $tsIP"

      - name: Export PATH for tools
        run: |
          echo "PATH=/usr/local/go/bin:$HOME/go/bin:$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          export PATH=/usr/local/go/bin:$HOME/go/bin:$HOME/.local/bin:$PATH

      - name: Install Go, Python, and Tools
        run: |
          set -euo pipefail
          sudo apt update -y
          sudo apt install -y python3 python3-pip python3-venv git curl wget unzip build-essential ca-certificates jq net-tools

          # Upgrade pip for user
          python3 -m pip install --upgrade --user pip setuptools wheel

          # ---------- Install latest Go ----------
          LATEST_GO=$(curl -fsS https://go.dev/VERSION?m=text | head -n 1)
          echo "Detected Go: ${LATEST_GO}"
          TGZ="/tmp/${LATEST_GO}.linux-amd64.tar.gz"
          wget -q -O "${TGZ}" "https://go.dev/dl/${LATEST_GO}.linux-amd64.tar.gz"
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf "${TGZ}"
          rm -f "${TGZ}"
          mkdir -p "$HOME/go/bin"
          export PATH=/usr/local/go/bin:$HOME/go/bin:$HOME/.local/bin:$PATH

          # ---------- Install ffuf ----------
          if ! command -v ffuf >/dev/null 2>&1; then
            /usr/local/go/bin/go install github.com/ffuf/ffuf/v2@latest || go install github.com/ffuf/ffuf/v2@latest
            sudo ln -sf "$HOME/go/bin/ffuf" /usr/local/bin/ffuf || true
          fi

          # ---------- Install httpx (ProjectDiscovery) ----------
          if ! command -v httpx >/dev/null 2>&1; then
            /usr/local/go/bin/go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest || go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
            sudo ln -sf "$HOME/go/bin/httpx" /usr/local/bin/httpx || true
          fi

          # ---------- Install dirsearch ----------
          TOOLS_DIR="$HOME/tools"
          DIRSEARCH_DIR="$TOOLS_DIR/dirsearch"
          mkdir -p "$TOOLS_DIR"
          if [ ! -d "$DIRSEARCH_DIR" ]; then
            git clone --depth 1 https://github.com/maurosoria/dirsearch.git "$DIRSEARCH_DIR"
          else
            git -C "$DIRSEARCH_DIR" pull --rebase --quiet || true
          fi
          # install python requirements to user
          if [ -f "$DIRSEARCH_DIR/requirements.txt" ]; then
            python3 -m pip install --user -r "$DIRSEARCH_DIR/requirements.txt" || python3 -m pip install --user requests termcolor
          else
            python3 -m pip install --user requests termcolor
          fi

      - name: Create dirsearch wrapper
        run: |
          sudo tee /usr/local/bin/dirsearch > /dev/null << 'EOF'
#!/usr/bin/env bash
python3 "$HOME/tools/dirsearch/dirsearch.py" "$@"
EOF
          sudo chmod +x /usr/local/bin/dirsearch

      - name: Install SecLists
        run: |
          WORDLIST_DIR="$HOME/wordlists/SecLists"
          mkdir -p "$HOME/wordlists"
          if [ ! -d "$WORDLIST_DIR" ]; then
            git clone --depth 1 https://github.com/danielmiessler/SecLists.git "$WORDLIST_DIR"
          else
            git -C "$WORDLIST_DIR" pull --rebase --quiet || true
          fi

      - name: Run quick checks for httpx & dirsearch
        run: |
          set -euo pipefail
          export PATH=/usr/local/go/bin:$HOME/go/bin:$HOME/.local/bin:$PATH

          echo "----- httpx check -----"
          if command -v httpx >/dev/null 2>&1; then
            httpx -h | head -n 5 || echo "httpx: help printed non-zero"
            echo "httpx binary at: $(which httpx)"
          else
            echo "httpx: NOT FOUND in PATH"
          fi

          echo "----- dirsearch check -----"
          if command -v dirsearch >/dev/null 2>&1; then
            dirsearch -h | head -n 8 || echo "dirsearch: help printed non-zero"
            echo "dirsearch wrapper at: $(which dirsearch)"
          else
            echo "dirsearch: NOT FOUND in PATH"
          fi

      - name: Verify SSH Access
        run: |
          echo "✅ VPS ready with pentest tools!"
          echo "IP: $TAILSCALE_IP"
          echo "User: root"
          echo "Pass: admin@123"

      - name: Keep VPS Alive
        run: |
          while true; do
            echo "[$(date)] VPS running with pentest tools..."
            sleep 300
          done
